"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.timeFormatComment = exports.removeVietnameseTones = exports.coverSlug = exports.cn = exports.capitalizeText = exports.Validator = exports.TextHandler = exports.Debounced = exports.CheckTypeImage = exports.handleSort = exports.createLogger = void 0;
const logger_lib_1 = require("./package/logger.lib");
exports.createLogger = logger_lib_1.default;
const sort_lib_1 = require("./package/sort.lib");
exports.handleSort = sort_lib_1.default;
const text_lib_1 = require("./package/text.lib");
Object.defineProperty(exports, "CheckTypeImage", { enumerable: true, get: function () { return text_lib_1.CheckTypeImage; } });
Object.defineProperty(exports, "Debounced", { enumerable: true, get: function () { return text_lib_1.Debounced; } });
Object.defineProperty(exports, "TextHandler", { enumerable: true, get: function () { return text_lib_1.TextHandler; } });
Object.defineProperty(exports, "Validator", { enumerable: true, get: function () { return text_lib_1.Validator; } });
Object.defineProperty(exports, "capitalizeText", { enumerable: true, get: function () { return text_lib_1.capitalizeText; } });
Object.defineProperty(exports, "cn", { enumerable: true, get: function () { return text_lib_1.cn; } });
Object.defineProperty(exports, "coverSlug", { enumerable: true, get: function () { return text_lib_1.coverSlug; } });
Object.defineProperty(exports, "removeVietnameseTones", { enumerable: true, get: function () { return text_lib_1.removeVietnameseTones; } });
Object.defineProperty(exports, "timeFormatComment", { enumerable: true, get: function () { return text_lib_1.timeFormatComment; } });
const Utils = require("./package/text.lib");
exports.default = Utils;
